/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : mihkel
 * Created : 09/02/2015 04:48:32
 */

package eu.onepay.payment.bank.ee;

import static org.junit.Assert.*;

import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.Signature;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;

import org.junit.Test;

import eu.onepay.payment.bank.ee.BankEE;

public class BankTest {

    private BankEE bank = new BankEE();
    private String alias = "1";

    /**
     * 
     * @see eu.onepay.payment.bank.ee.BankEE#getSignature(boolean,String)
     */
    @Test
    public void getSignature() {
        try {
            Signature signature = bank.getSignature(false, alias);
            assertNotNull("signature cannot be null", signature);
        } catch (NoSuchAlgorithmException | UnrecoverableKeyException | InvalidKeyException | KeyStoreException
                | CertificateException | IOException noSuchAlgorithmException) {
            noSuchAlgorithmException.printStackTrace();
            // System.out.println(NoSuchAlgorithmException.class.getName());
            fail("Test for getSignature failed " + noSuchAlgorithmException.getMessage());
        }
    }

    /**
     *
     * @see eu.onepay.payment.bank.ee.BankEE#generateMac(String[],String)
     */
    @Test
    public void generateMac() {
        try {

            String[] str = new String[] { "asd" };
            String result = bank.generateMac(str);
            String trueResult = "003"+str[0];
            assertNotNull("result cannot be null", result);
            assertTrue("Result is '" + result +"' but should be '" + trueResult +"'", result.equals(trueResult));

        } catch (Exception exception) {
            exception.printStackTrace();
            // System.out.println(Exception.class.getName());
            fail("Test for generateMac failed " + exception.getMessage());
        }
    }

}
